### ISSUE TITLE
Update EIA API to V2

### ISSUE THREAD

**Issue by gschivley** [jdechalendar/gridemissions#9]
EIA is shutting down (or might have already shut down?) V1 of their API. Fortunately they are providing an easily accessed translator for V1 seriesIDs.

![image](https://user-images.githubusercontent.com/10373332/212360012-64e025e7-90dd-49af-b9d0-d77460791343.png)

**Comment by jdechalendar** [comment]
Thanks for pointing this out! Will work on a patch. Doesn't seem to have affected the visualization [here](https://energy.stanford.edu/gridemissions) yet.

**Comment by jdechalendar** [comment]
v2 has been in effect since March 13th, 2023.
